spring:
  flyway:
    enabled: false
  application:
    name: pc-accounting
  datasource:
    url: 'jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}'
    username: '${POSTGRES_USERNAME}'
    password: '${POSTGRES_PASSWORD}'
    driver-class-name: org.postgresql.Driver
  output:
    ansi:
      enabled: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        highlight_sql: true
        use_sql_comments: true
        format_sql: true
server:
  port: '${SERVER_PORT}'
  error:
    whitelabel:
      enabled: true
    include-stacktrace: never
    include-exception: true
    include-binding-errors: never
    include-message: always

